export const TOP_SPANISH_CITIES: string[] = [
  'Madrid',
  'Barcelona',
  'Valencia',
  'Sevilla',
  'Zaragoza',
  'Málaga',
  'Murcia',
  'Palma de Mallorca',
  'Las Palmas de Gran Canaria',
  'Bilbao',
  'Alicante',
  'Córdoba',
  'Valladolid',
  'Vigo',
  'Gijón',
  'L\'Hospitalet de Llobregat',
  'A Coruña',
  'Vitoria-Gasteiz',
  'Granada',
  'Elche',
  'Oviedo',
  'Badalona',
  'Cartagena',
  'Terrassa',
  'Jerez de la Frontera',
  'Sabadell',
  'Santa Cruz de Tenerife',
  'Móstoles',
  'Alcalá de Henares',
  'Fuenlabrada',
  'Pamplona',
  'Almería',
  'Leganés',
  'San Sebastián',
  'Santander',
  'Castellón de la Plana',
  'Burgos',
  'Albacete',
  'Alcorcón',
  'Getafe',
  'Salamanca',
  'Logroño',
  'San Cristóbal de La Laguna',
  'Huelva',
  'Badajoz',
  'Tarragona',
  'Lleida',
  'Marbella',
  'León',
  'Cádiz',
  'Girona',
  'Toledo',
  'Benidorm',
  'Torremolinos',
  'Torrevieja',
  'Fuengirola',
  'Estepona',
  'Ibiza',
  'Tenerife',
];
